# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
post_install do |installer|
  flutter_post_install(installer)
end
target 'flutter_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)
  pod 'TZImagePickerController'
  
  # Pods for flutter_test
  target 'flutter_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flutter_testUITests' do
    # Pods for testing
  end

end
